import type { Product } from "@/lib/types";

const updatedAt = "2026-07-30T08:00:00.000Z";

export const seedProducts: Product[] = [
  {
    id: "tire-pilot-sport-5",
    sku: "T-MI-PS5-2254518",
    externalId: "1C-000001",
    kind: "tire",
    brand: "Michelin",
    model: "Pilot Sport 5",
    subtitle: "225/45 R18 95Y XL",
    width: 225,
    profile: 45,
    diameter: 18,
    season: "summer",
    studded: false,
    runflat: false,
    price: 18490,
    oldPrice: 20990,
    stock: 12,
    reserved: 2,
    warehouse: "Кемерово · Основной склад",
    rating: 4.9,
    reviews: 128,
    tags: ["Выбор экспертов", "XL"],
    country: "Франция",
    featured: true,
    compatibleCars: ["BMW 3 Series", "Audi A4", "Mercedes-Benz C-Class", "Kia K5"],
    updatedAt,
  },
  {
    id: "tire-continental-premium",
    sku: "T-CO-PC7-2055516",
    externalId: "1C-000002",
    kind: "tire",
    brand: "Continental",
    model: "PremiumContact 7",
    subtitle: "205/55 R16 91V",
    width: 205,
    profile: 55,
    diameter: 16,
    season: "summer",
    studded: false,
    runflat: false,
    price: 12890,
    stock: 24,
    reserved: 4,
    warehouse: "Кемерово · Основной склад",
    rating: 4.8,
    reviews: 94,
    tags: ["Тихая"],
    country: "Германия",
    compatibleCars: ["Volkswagen Passat", "Skoda Octavia", "Toyota Corolla", "Kia Ceed"],
    updatedAt,
  },
  {
    id: "tire-hakkapeliitta-10",
    sku: "T-IK-HAK10-2255517",
    externalId: "1C-000003",
    kind: "tire",
    brand: "Ikon Tyres",
    model: "Hakkapeliitta 10",
    subtitle: "225/55 R17 101T XL",
    width: 225,
    profile: 55,
    diameter: 17,
    season: "winter",
    studded: true,
    runflat: false,
    price: 16990,
    oldPrice: 18490,
    stock: 18,
    reserved: 1,
    warehouse: "Кемерово · Основной склад",
    rating: 4.9,
    reviews: 167,
    tags: ["Шипы", "XL"],
    country: "Россия",
    compatibleCars: ["Toyota Camry", "Hyundai Sonata", "Kia K5", "Subaru Forester"],
    updatedAt,
  },
  {
    id: "tire-pirelli-ice-zero",
    sku: "T-PI-IZF-2355518",
    externalId: "1C-000004",
    kind: "tire",
    brand: "Pirelli",
    model: "Ice Zero FR",
    subtitle: "235/55 R18 104H XL",
    width: 235,
    profile: 55,
    diameter: 18,
    season: "winter",
    studded: false,
    runflat: false,
    price: 17390,
    stock: 7,
    reserved: 0,
    warehouse: "Кемерово · Основной склад",
    rating: 4.7,
    reviews: 73,
    tags: ["Липучка", "XL"],
    country: "Италия",
    compatibleCars: ["Toyota RAV4", "Volkswagen Tiguan", "Kia Sportage", "Hyundai Tucson"],
    updatedAt,
  },
  {
    id: "tire-goodyear-eagle",
    sku: "T-GY-EF6-2454019",
    externalId: "1C-000005",
    kind: "tire",
    brand: "Goodyear",
    model: "Eagle F1 Asymmetric 6",
    subtitle: "245/40 R19 98Y XL",
    width: 245,
    profile: 40,
    diameter: 19,
    season: "summer",
    studded: false,
    runflat: true,
    price: 22490,
    oldPrice: 23990,
    stock: 8,
    reserved: 2,
    warehouse: "Кемерово · Основной склад",
    rating: 4.9,
    reviews: 56,
    tags: ["RunFlat", "Sport"],
    country: "Германия",
    featured: true,
    compatibleCars: ["BMW 5 Series", "Audi A6", "Mercedes-Benz E-Class"],
    updatedAt,
  },
  {
    id: "tire-yokohama-geolandar",
    sku: "T-YO-G015-2656018",
    externalId: "1C-000006",
    kind: "tire",
    brand: "Yokohama",
    model: "Geolandar A/T G015",
    subtitle: "265/60 R18 110H",
    width: 265,
    profile: 60,
    diameter: 18,
    season: "all-season",
    studded: false,
    runflat: false,
    price: 21390,
    stock: 16,
    reserved: 3,
    warehouse: "Кемерово · Основной склад",
    rating: 4.8,
    reviews: 114,
    tags: ["All Terrain"],
    country: "Япония",
    compatibleCars: ["Toyota Land Cruiser Prado", "Mitsubishi Pajero Sport", "Haval H9"],
    updatedAt,
  },
  {
    id: "tire-bridgestone-turanza",
    sku: "T-BS-T6-2155517",
    externalId: "1C-000007",
    kind: "tire",
    brand: "Bridgestone",
    model: "Turanza 6",
    subtitle: "215/55 R17 98W XL",
    width: 215,
    profile: 55,
    diameter: 17,
    season: "summer",
    studded: false,
    runflat: false,
    price: 14790,
    stock: 20,
    reserved: 5,
    warehouse: "Кемерово · Основной склад",
    rating: 4.7,
    reviews: 61,
    tags: ["Комфорт"],
    country: "Япония",
    compatibleCars: ["Toyota Camry", "Skoda Octavia", "Volkswagen Passat", "Mazda 6"],
    updatedAt,
  },
  {
    id: "tire-hankook-kinergy",
    sku: "T-HK-4S2-2055516",
    externalId: "1C-000008",
    kind: "tire",
    brand: "Hankook",
    model: "Kinergy 4S2",
    subtitle: "205/55 R16 94V XL",
    width: 205,
    profile: 55,
    diameter: 16,
    season: "all-season",
    studded: false,
    runflat: false,
    price: 10890,
    stock: 32,
    reserved: 6,
    warehouse: "Кемерово · Основной склад",
    rating: 4.6,
    reviews: 89,
    tags: ["4 сезона"],
    country: "Корея",
    compatibleCars: ["Kia Ceed", "Hyundai Elantra", "Skoda Octavia", "Toyota Corolla"],
    updatedAt,
  },
  {
    id: "wheel-vossen-hf5",
    sku: "W-VO-HF5-1985",
    externalId: "1C-000101",
    kind: "wheel",
    brand: "Vossen",
    model: "HF-5",
    subtitle: "R19 × 8.5J 5×112 ET35",
    width: 0,
    profile: 0,
    diameter: 19,
    season: "none",
    studded: false,
    runflat: false,
    pcd: "5×112",
    offset: 35,
    centerBore: 66.6,
    color: "Anthracite",
    price: 46900,
    stock: 4,
    reserved: 0,
    warehouse: "Кемерово · Основной склад",
    rating: 5,
    reviews: 21,
    tags: ["Flow Formed"],
    country: "США",
    featured: true,
    compatibleCars: ["BMW 3 Series", "Audi A4", "Mercedes-Benz C-Class"],
    updatedAt,
  },
  {
    id: "wheel-bbs-xr",
    sku: "W-BB-XR-1880",
    externalId: "1C-000102",
    kind: "wheel",
    brand: "BBS",
    model: "XR",
    subtitle: "R18 × 8J 5×112 ET40",
    width: 0,
    profile: 0,
    diameter: 18,
    season: "none",
    studded: false,
    runflat: false,
    pcd: "5×112",
    offset: 40,
    centerBore: 82,
    color: "Platinum Silver",
    price: 32900,
    oldPrice: 35900,
    stock: 8,
    reserved: 2,
    warehouse: "Кемерово · Основной склад",
    rating: 4.9,
    reviews: 38,
    tags: ["Made in Germany"],
    country: "Германия",
    compatibleCars: ["Audi A4", "Volkswagen Passat", "Skoda Octavia"],
    updatedAt,
  },
  {
    id: "wheel-kik-ks741",
    sku: "W-KK-KS741-1775",
    externalId: "1C-000103",
    kind: "wheel",
    brand: "K&K",
    model: "КС741",
    subtitle: "R17 × 7.5J 5×114.3 ET45",
    width: 0,
    profile: 0,
    diameter: 17,
    season: "none",
    studded: false,
    runflat: false,
    pcd: "5×114.3",
    offset: 45,
    centerBore: 67.1,
    color: "Алмаз чёрный",
    price: 12490,
    stock: 14,
    reserved: 1,
    warehouse: "Кемерово · Основной склад",
    rating: 4.7,
    reviews: 44,
    tags: ["Гарантия 3 года"],
    country: "Россия",
    compatibleCars: ["Kia K5", "Hyundai Sonata", "Toyota Camry"],
    updatedAt,
  },
  {
    id: "wheel-rial-lucca",
    sku: "W-RI-LUCCA-1875",
    externalId: "1C-000104",
    kind: "wheel",
    brand: "Rial",
    model: "Lucca",
    subtitle: "R18 × 7.5J 5×108 ET45",
    width: 0,
    profile: 0,
    diameter: 18,
    season: "none",
    studded: false,
    runflat: false,
    pcd: "5×108",
    offset: 45,
    centerBore: 63.4,
    color: "Diamond Black",
    price: 21900,
    stock: 6,
    reserved: 0,
    warehouse: "Кемерово · Основной склад",
    rating: 4.8,
    reviews: 17,
    tags: ["TÜV"],
    country: "Германия",
    compatibleCars: ["Volvo XC60", "Ford Mondeo", "Land Rover Range Rover Evoque"],
    updatedAt,
  },
];

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("ru-RU").format(price) + " ₽";

export const seasonLabels = {
  summer: "Летние",
  winter: "Зимние",
  "all-season": "Всесезонные",
  none: "Не применимо",
} as const;
